### ISSUE TITLE
[FEATURE REQUEST] Add issue & PR template.

### ISSUE THREAD

**Issue by KendallDoesCoding** [TechStudent11/heroku-portfolio#14]
Add the following:

[Issue Templates](https://github.com/KendallDoesCoding/mogul-christmas/tree/main/.github/ISSUE_TEMPLATE) - Basic Issue Templates
[PR Template](https://github.com/codyseibert/fire-stone-hosting/blob/master/.github/pull_request_template.md) - Fallback PR Template

**Comment by FahimFBA** [comment]
If this issue is still unassigned, then I would like to resolve that. Let me know what you think about this.

**Comment by KendallDoesCoding** [comment]
> If this issue is still unassigned, then I would like to resolve that. Let me know what you think about this.

Thanks for requesting to be assigned. Will assign you.
