### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by KendallDoesCoding** [TechStudent11/heroku-portfolio#15]
Your fine with MIT license or do you want "The Unlicense" for this repo @TechStudent11?

**Comment by TechStudent10** [comment]
I'm pretty sure MIT is fine. But what is the "The Unlicense" license?

**Comment by KendallDoesCoding** [comment]
> I'm pretty sure MIT is fine. But what is the "The Unlicense" license?

I thought you had it in one repo of yours?

**Comment by KendallDoesCoding** [comment]
The Unlicense LICENSE: https://github.com/TechStudent11/heroku-portfolio/community/license/new?branch=master&template=unlicense
